#!/usr/bin/env python3

import json
import os
import tempfile
from datetime import datetime, timedelta, timezone

from parse_share_analytics import LOGS_DIR, find_sharelog_files
import analytics_state
import ckpool_native_stats
import histogram_builder
import block_progress
import worker_sessions

# Phase E Milestone 31: additive, backward-compatible schema change
# (session_accepted_count/session_rejected_count/session_started_at on
# workers only) -- bumped the minor version again per this project's own
# versioning discipline (Milestone 30 bumped 1.3 -> 1.4 for the same
# reason).
SCHEMA_VERSION = "1.5"
GENERATOR = "analytics_builder.py"
ANALYTICS_OUTPUT_PATH = "/home/damopool/ckpool-solo/ckpool/analytics.json"

_EMPTY_HASHRATES = {"hashrate_1m": None, "hashrate_24h": None}


def build_analytics(
    logs_dir=None,
    now=None,
    state_path=None,
    histogram_state_path=None,
    network_diff_state_path=None,
    worker_sessions_state_path=None,
):
    """now, if supplied, must be a timezone-aware UTC datetime. state_path
    overrides analytics_state.STATE_PATH; histogram_state_path overrides
    histogram_builder.STATE_PATH; network_diff_state_path overrides
    ckpool_native_stats.NETWORK_DIFF_STATE_PATH; worker_sessions_state_path
    overrides worker_sessions.STATE_PATH -- always pass isolated paths in
    tests to avoid touching the real incremental state."""
    if logs_dir is None:
        logs_dir = LOGS_DIR
    if now is None:
        now = datetime.now(timezone.utc)
    if state_path is None:
        state_path = analytics_state.STATE_PATH
    if histogram_state_path is None:
        histogram_state_path = histogram_builder.STATE_PATH
    if network_diff_state_path is None:
        network_diff_state_path = ckpool_native_stats.NETWORK_DIFF_STATE_PATH
    if worker_sessions_state_path is None:
        worker_sessions_state_path = worker_sessions.STATE_PATH
    today = now.date()
    yesterday = today - timedelta(days=1)

    state = analytics_state.update_state(logs_dir, now, state_path=state_path)
    merged = analytics_state.merge_state_to_analytics(state, now, today, yesterday)

    source_files = find_sharelog_files(logs_dir)

    # Milestone 28: CKPool's own native hashrate figures, read and merged
    # in here rather than inside analytics_state.py -- deliberately kept
    # separate from that module's sharelog-incremental engine (see
    # ckpool_native_stats.py's own module comment for why). Merged only
    # into users/workers analytics_state.py already produced from
    # sharelog data -- a native file with no sharelog-derived counterpart
    # (implausible in practice, but not assumed impossible) contributes no
    # phantom user/worker entry of its own.
    native = ckpool_native_stats.read_native_hashrates(logs_dir)
    network_difficulty = ckpool_native_stats.read_network_difficulty(logs_dir, state_path=network_diff_state_path)

    # Milestone 29: the Share Difficulty Distribution Histogram, generated
    # by its own dedicated, independent module for the same
    # separation-of-concerns reason as the native-hashrate reads above.
    # Same "augment an already-existing entry, never create a phantom
    # one" merge discipline: a user/worker analytics_state.py never saw
    # any share for at all simply isn't in merged["users"]/["workers"] to
    # begin with, so there's nothing to merge onto.
    histograms = histogram_builder.build_histograms(logs_dir, now, state_path=histogram_state_path)

    # Milestone 30: Block Progress Analytics -- a pure derived computation
    # from values already produced above (each scope's own best_share_ever
    # sdiff, and the single pool-wide network_difficulty), needing no new
    # data source or incremental state of its own. See block_progress.py's
    # own module comment for why it's still a dedicated module rather than
    # inlined here.
    def best_sdiff(record):
        best_share_ever = record.get("best_share_ever")
        return best_share_ever["sdiff"] if best_share_ever else None

    pool_out = {
        **merged["pool"],
        **native["pool"],
        "network_difficulty": network_difficulty,
        "difficulty_histogram": histograms["pool"],
        "block_progress": block_progress.compute_block_progress(best_sdiff(merged["pool"]), network_difficulty),
    }

    users_out = {}
    for username, record in merged["users"].items():
        user_native = native["users"].get(username, dict(_EMPTY_HASHRATES))
        user_histogram = histograms["users"].get(username, histogram_builder.empty_histogram_dataset_pair())
        user_block_progress = block_progress.compute_block_progress(best_sdiff(record), network_difficulty)
        users_out[username] = {
            **record,
            **user_native,
            "difficulty_histogram": user_histogram,
            "block_progress": user_block_progress,
        }

    # Milestone 31: Worker Session Accepted/Rejected Counts -- generated by
    # its own dedicated, independent module for the same separation-of-
    # concerns reason as histogram_builder.py/ckpool_native_stats.py.
    # Worker-scope only (Human-approved scope: pool/users stay lifetime).
    worker_sessions_data = worker_sessions.build_worker_sessions(logs_dir, state_path=worker_sessions_state_path)

    workers_out = {}
    for workername, record in merged["workers"].items():
        worker_native = native["workers"].get(workername, dict(_EMPTY_HASHRATES))
        worker_histogram = histograms["workers"].get(workername, histogram_builder.empty_histogram_dataset_pair())
        worker_block_progress = block_progress.compute_block_progress(best_sdiff(record), network_difficulty)
        worker_session = worker_sessions_data.get(workername, worker_sessions.empty_worker_session())
        workers_out[workername] = {
            **record,
            **worker_native,
            "difficulty_histogram": worker_histogram,
            "block_progress": worker_block_progress,
            **worker_session,
        }

    metadata = {
        "schema_version": SCHEMA_VERSION,
        "generated_at": now.isoformat(),
        "generator": GENERATOR,
        "source_files_scanned": len(source_files),
        "pool_start_date": merged["pool_start_date"],
        "share_records_processed": merged["share_records_processed"],
    }

    return {
        "metadata": metadata,
        "pool": pool_out,
        "users": users_out,
        "workers": workers_out,
        "daily_bests": merged["daily_bests"],
        "live_ticker": merged["live_ticker"],
    }


def write_analytics(data, path):
    directory = os.path.dirname(path) or "."
    fd, tmp_path = tempfile.mkstemp(prefix=".analytics.", suffix=".tmp", dir=directory)
    try:
        with os.fdopen(fd, "w") as f:
            json.dump(data, f, indent=2)
        # mkstemp creates the file 0600 (owner-only); analytics.json is
        # meant to be read by other processes (e.g. a future webserver), so
        # widen it to world-readable before the atomic replace.
        os.chmod(tmp_path, 0o644)
        os.replace(tmp_path, path)
    except BaseException:
        try:
            os.remove(tmp_path)
        except OSError:
            pass
        raise


def main():
    data = build_analytics()
    write_analytics(data, ANALYTICS_OUTPUT_PATH)
    print(f"Wrote {ANALYTICS_OUTPUT_PATH}")


if __name__ == "__main__":
    main()
