// Historical Analytics page -- docs/ARCHITECTURE.md Section 4/5/9
// (`/app/#/history`). Composes ChartPanel x N per Section 5's
// component list -- no StatTile, no DataTable, no SearchBox.
// shell.js's APP_NAV_ITEMS already had a History nav entry since
// Milestone 5, so no shell.js change is needed here.
//
// The first page in this project that does NOT read analytics.json.
// docs/ARCHITECTURE.md Section 25 explicitly defers multi-day history
// to a separate, not-yet-built analytics_history.json
// (PROJECT_LOG.md 2026-07-15); analytics.json's own daily_bests holds
// only today and yesterday. What already exists, today, in production
// is the *existing*, CLAUDE.md-protected `historical_data.json` --
// generated by the pre-existing parse_pool_stats.py (CLAUDE.md: "Do
// not modify the existing parser... Do not modify historical_data.json
// structure"), already served at a real, already-existing Nginx
// location (`/historical_data`, confirmed by reading
// /etc/nginx/sites-available/default -- no new Nginx work needed here,
// unlike analytics.json's own still-pending Section 15 cutover item).
// This page only ever reads that file; it never writes to it, and
// nothing here depends on or assumes any future analytics_history.json
// contract.
//
// Because this is a different file with a different, pre-existing
// shape (a bare JSON array of `{timestamp, pool_stats: {...}}`
// snapshots, not an object with `metadata`/`pool`/`users`/etc.), this
// page deliberately does NOT reuse several analytics.json-specific
// primitives that would silently misbehave against this shape:
//   - core/errors.js's `validateSchema` checks for analytics.json's own
//     top-level keys and `metadata.schema_version` -- neither exists
//     on this array, so it would reject every real response. A small,
//     page-local `isValidHistoricalData` checks the one thing that
//     actually matters here (the payload is an array).
//   - core/errors.js's `describeFetchError` says "analytics
//     service"/"analytics data," which would be a factually wrong
//     message for a `/historical_data` failure. A page-local
//     `describeHistoryFetchError` mirrors its exact kind-based
//     branching with corrected wording -- not a duplicate of its
//     logic in spirit, just correctly scoped wording for a different
//     data source, kept local rather than added to a shared module for
//     its only consumer (the same "extract once a second consumer
//     needs it" discipline already established for describeFetchError
//     itself).
//   - core/api.js's built-in staleness detection reads
//     `payload.metadata.generated_at`, which this array does not have
//     -- passing `staleAfterMs` straight through to fetchEndpoint would
//     make every response report `isStale: true` unconditionally, a
//     wrong result, not a missing one. Staleness here is instead
//     computed locally, in deriveHistoryState, from the *data's own*
//     freshness signal: the most recent snapshot's own `timestamp`.
//   - core/state.js's `analytics`/`analyticsFetchedAt` fields are
//     documented as holding "the last-fetched analytics.json payload"
//     specifically, shared because multiple pages consume it. Nothing
//     else in this project reads historical_data.json, so there is no
//     sharing need, and writing this array into that slot would
//     corrupt its documented, single-purpose meaning for the one
//     narrow window before this page's next fetch overwrites it. This
//     page's fetched payload lives only in its own module closure.
//
// pool_stats' own numeric fields arrive as legacy, human-formatted
// strings ("14.2T", "241.08G"), not raw numbers -- parseSizeString
// below is the first "parse a formatted string back into a number"
// utility in this project (every existing core/format.js helper only
// goes the other direction). Kept page-local rather than added to
// core/format.js for the same single-consumer reasoning as above.
//
// No prototype-chain risk and no free-text/XSS surface exists on this
// page at all: historical_data.json is an array of snapshots (never a
// dictionary keyed by username/workername), and this first version
// deliberately shows pool-level aggregates only -- no per-user
// breakdown, so no attacker-influenceable string (a username, an
// agent string) is read or rendered anywhere in this file.
//
// The four charts below are the first genuine time-series charts in
// this project -- every prior chart (Overview/Pool/User Detail/Worker
// Detail) plots a small, fixed category axis (15m/1h/24h, p50/p90/p99),
// never real timestamps. ECharts' own `xAxis: {type: "time"}` is used
// here instead of hand-rolling date-bucketing/label logic -- it is
// built for exactly this and correctly adapts its own tick labels to
// however wide a range the data actually spans, which a fixed
// `formatTimestamp` (core/format.js's HH:MM-only formatter, sufficient
// for every prior chart's same-day rolling windows) cannot do once the
// range can span multiple days.
//
// Also the first page with more than one chart -- defaultRender below
// generalises the single-canvas-swap technique every prior chart page
// uses to an *array* of canvas nodes, reused/created/disposed
// positionally (the charts are always rendered in the same fixed
// order, so index-based matching is sufficient and needs no per-chart
// identifier).

import { el, specToDom } from "../core/dom.js";
import { fetchEndpoint, startPolling } from "../core/api.js";
import { getStaleness } from "../core/errors.js";
import { getState, subscribe } from "../core/state.js";
import { formatSdiff, formatRelativeTime } from "../core/format.js";
import { cardSpec } from "../components/card.js";
import { emptyStateSpec } from "../components/empty-state.js";
import { loadingSkeletonSpec } from "../components/loading-skeleton.js";
import { errorBannerSpec } from "../components/error-banner.js";
import { chartPanelSpec } from "../components/chart-panel.js";
import { createChart } from "../charts/chart.js";
import { buildEChartsTheme, readThemeTokens } from "../charts/theme-echarts.js";

const HISTORY_ENDPOINT = "/historical_data";

export const route = { pattern: "/history", name: "history" };

// -------------------------------------------------------------------
// Pure parsing/formatting for this legacy, string-encoded data source
// -------------------------------------------------------------------

const SIZE_UNIT_FACTORS = [
  { suffix: "P", factor: 1e15 },
  { suffix: "T", factor: 1e12 },
  { suffix: "G", factor: 1e9 },
  { suffix: "M", factor: 1e6 },
  { suffix: "K", factor: 1e3 },
];

// Accepts either the legacy suffixed string ("14.2T") or an already-
// numeric value (defensive: nothing in this project's own docs
// guarantees this pre-existing file's field types, only the sample
// data observed) -- either way returns a plain number of base units,
// or null for anything that parses as neither.
export function parseSizeString(value) {
  if (typeof value === "number") {
    return Number.isFinite(value) ? value : null;
  }
  if (typeof value !== "string") {
    return null;
  }
  const match = value.trim().match(/^(-?\d+(?:\.\d+)?)\s*([KMGTP]?)$/i);
  if (!match) return null;
  const [, numberPart, unitPart] = match;
  const unit = SIZE_UNIT_FACTORS.find((u) => u.suffix === unitPart.toUpperCase());
  return parseFloat(numberPart) * (unit ? unit.factor : 1);
}

function scaleBySizeUnit(value) {
  const abs = Math.abs(value);
  const unit = SIZE_UNIT_FACTORS.find((u) => abs >= u.factor);
  return unit ? { scaled: value / unit.factor, suffix: unit.suffix } : { scaled: value, suffix: "" };
}

export function formatHashrate(value) {
  if (!Number.isFinite(value)) return null;
  const { scaled, suffix } = scaleBySizeUnit(value);
  return `${scaled.toFixed(2)} ${suffix}H/s`;
}

// A compact axis-tick-friendly form of a difficulty value -- distinct
// from formatSdiff (core/format.js), which every other page in this
// project already uses for a *full*, comma-separated difficulty number
// in prose/table text, where space isn't constrained the way a chart
// Y-axis tick label's is. Both are used below: this one for the chart
// itself, formatSdiff for the accessible summary text, matching the
// established project-wide difficulty display convention there.
export function formatCompactDifficulty(value) {
  if (!Number.isFinite(value)) return null;
  const { scaled, suffix } = scaleBySizeUnit(value);
  return suffix ? `${scaled.toFixed(2)} ${suffix}` : scaled.toFixed(2);
}

function formatCount(n) {
  return Number.isFinite(n) ? n.toLocaleString("en-US") : null;
}

// -------------------------------------------------------------------
// Pure data transformation
// -------------------------------------------------------------------

// A malformed entry (no pool_stats, no timestamp) is dropped rather
// than producing a broken chart point -- the same "degrade gracefully"
// discipline applied everywhere else in this project, here at the
// whole-snapshot level. Defensively sorted ascending by timestamp: the
// live_ticker precedent (search.js/pages/ticker.js) trusts its own
// documented "sorted newest first" contract because that contract is
// this project's own, but historical_data.json's ordering is not
// documented anywhere in CLAUDE.md or the architecture -- it is a
// pre-existing file this project does not own the contract for, so a
// defensive sort costs little and guarantees a correctly-ordered
// x-axis regardless of what the legacy parser's append order actually
// is.
function isParseableTimestamp(value) {
  return typeof value === "string" && !Number.isNaN(new Date(value).getTime());
}

export function transformHistoryData(payload) {
  const entries = Array.isArray(payload) ? payload : [];
  const snapshots = entries
    // A truthy-but-unparseable timestamp (a corrupted string) must be
    // dropped here, alongside a genuinely-missing one -- otherwise
    // new Date(...).getTime() downstream (the sort comparator below,
    // and toTimeSeries' own x-axis positions) silently yields NaN,
    // producing an unpredictable sort order and a real, garbage point
    // plotted on every chart rather than the entry being excluded the
    // way a missing timestamp already is.
    .filter((entry) => entry && isParseableTimestamp(entry.timestamp) && entry.pool_stats)
    .map((entry) => {
      const stats = entry.pool_stats;
      return {
        timestamp: entry.timestamp,
        hashrate: parseSizeString(stats.pool_hashrate),
        acceptedShares: Number.isFinite(stats.accepted_shares) ? stats.accepted_shares : null,
        rejectedShares: Number.isFinite(stats.rejected_shares) ? stats.rejected_shares : null,
        highestDifficulty: parseSizeString(stats.highest_difficulty),
        workers: Number.isFinite(stats.workers) ? stats.workers : null,
        users: Number.isFinite(stats.users) ? stats.users : null,
      };
    })
    .sort((a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime());

  return { snapshots };
}

// The one structural check that actually matters for this shape --
// unlike core/errors.js's validateSchema (analytics.json's own
// metadata/schema_version keys, inapplicable here), this file is just
// a bare JSON array; anything else (an object, a string, a parse
// failure already caught upstream) is a genuine schema mismatch, not
// "empty."
export function isValidHistoricalData(payload) {
  if (!Array.isArray(payload)) {
    return { valid: false, reason: "not-an-array" };
  }
  return { valid: true, reason: null };
}

function describeHistoryFetchError(error) {
  if (!error) return "Something went wrong.";
  if (error.kind === "network") return "Could not reach the historical statistics service. Check your connection.";
  if (error.kind === "http") {
    const status = error.status ? ` (HTTP ${error.status})` : "";
    return `The historical statistics service returned an error${status}.`;
  }
  if (error.kind === "schema") return "The historical statistics data is in an unexpected format.";
  return "Something went wrong loading historical statistics data.";
}

function staleMessage(latestTimestampIso) {
  const relative = formatRelativeTime(latestTimestampIso);
  return relative
    ? `Data may be stale -- most recent snapshot ${relative}.`
    : "Data may be stale.";
}

// staleAfterMs (if supplied) is compared against the most recent
// snapshot's own timestamp -- there is no metadata.generated_at on
// this payload for core/api.js's built-in staleness mechanism to read,
// so it is deliberately not used here (see the module comment).
export function deriveHistoryState({ payload, error = null, staleAfterMs } = {}) {
  if (!payload) {
    return { status: "error", data: null, error, isStale: false };
  }
  const data = transformHistoryData(payload);
  const status = data.snapshots.length === 0 ? "empty" : "success";

  let isStale = false;
  if (status === "success" && Number.isFinite(staleAfterMs)) {
    const latest = data.snapshots[data.snapshots.length - 1];
    isStale = getStaleness(latest.timestamp, new Date(), staleAfterMs).isStale;
  }

  return { status, data, error, isStale };
}

// -------------------------------------------------------------------
// Pure chart data transformation
// -------------------------------------------------------------------

function toTimeSeries(snapshots, valueFn) {
  return snapshots
    .map((snapshot) => {
      const value = valueFn(snapshot);
      return value === null || value === undefined ? null : [new Date(snapshot.timestamp).getTime(), value];
    })
    .filter((point) => point !== null);
}

function baseLineChartOption(theme, { yAxisFormatter, legendNames } = {}) {
  return {
    backgroundColor: theme.backgroundColor || "transparent",
    textStyle: theme.textStyle || {},
    legend: legendNames ? { data: legendNames, textStyle: theme.textStyle || {}, top: 0 } : undefined,
    grid: { left: 72, right: 16, top: legendNames ? 40 : 24, bottom: 40, containLabel: true },
    xAxis: {
      type: "time",
      axisLine: theme.axisLine || {},
      axisLabel: theme.axisLabel || {},
    },
    yAxis: {
      type: "value",
      axisLine: theme.axisLine || {},
      axisLabel: yAxisFormatter ? { ...(theme.axisLabel || {}), formatter: yAxisFormatter } : theme.axisLabel || {},
      splitLine: theme.splitLine || {},
    },
  };
}

export function buildHashrateChartOption(snapshots, theme = {}) {
  return {
    ...baseLineChartOption(theme, { yAxisFormatter: (value) => formatHashrate(value) || value }),
    series: [
      {
        name: "Pool Hashrate",
        type: "line",
        showSymbol: false,
        data: toTimeSeries(snapshots, (s) => s.hashrate),
        itemStyle: { color: theme.accentColor || undefined },
        lineStyle: { color: theme.accentColor || undefined },
      },
    ],
  };
}

export function buildHashrateChartSummary(snapshots) {
  const values = snapshots.map((s) => s.hashrate).filter((v) => Number.isFinite(v));
  if (values.length === 0) return "Pool hashrate -- no data available.";
  const latest = formatHashrate(values[values.length - 1]);
  return `Pool hashrate over ${values.length} snapshots -- most recently ${latest || "no data"}.`;
}

export function buildSharesChartOption(snapshots, theme = {}) {
  return {
    ...baseLineChartOption(theme, {
      legendNames: ["Accepted", "Rejected"],
      yAxisFormatter: (value) => formatCount(value) || value,
    }),
    series: [
      { name: "Accepted", type: "line", showSymbol: false, data: toTimeSeries(snapshots, (s) => s.acceptedShares) },
      { name: "Rejected", type: "line", showSymbol: false, data: toTimeSeries(snapshots, (s) => s.rejectedShares) },
    ],
  };
}

export function buildSharesChartSummary(snapshots) {
  const accepted = snapshots.map((s) => s.acceptedShares).filter((v) => Number.isFinite(v));
  const rejected = snapshots.map((s) => s.rejectedShares).filter((v) => Number.isFinite(v));
  if (accepted.length === 0 && rejected.length === 0) return "Accepted and rejected shares -- no data available.";
  const latestAccepted = accepted.length > 0 ? formatCount(accepted[accepted.length - 1]) : "no data";
  const latestRejected = rejected.length > 0 ? formatCount(rejected[rejected.length - 1]) : "no data";
  return `Cumulative accepted and rejected shares over ${snapshots.length} snapshots -- most recently ${latestAccepted} accepted, ${latestRejected} rejected.`;
}

export function buildDifficultyChartOption(snapshots, theme = {}) {
  return {
    ...baseLineChartOption(theme, { yAxisFormatter: (value) => formatCompactDifficulty(value) || value }),
    series: [
      {
        name: "Highest Difficulty",
        type: "line",
        showSymbol: false,
        data: toTimeSeries(snapshots, (s) => s.highestDifficulty),
        itemStyle: { color: theme.accentColor || undefined },
        lineStyle: { color: theme.accentColor || undefined },
      },
    ],
  };
}

export function buildDifficultyChartSummary(snapshots) {
  const values = snapshots.map((s) => s.highestDifficulty).filter((v) => Number.isFinite(v));
  if (values.length === 0) return "Highest difficulty -- no data available.";
  const latest = formatSdiff(values[values.length - 1]);
  return `Highest recorded share difficulty over ${values.length} snapshots -- most recently ${latest || "no data"}.`;
}

export function buildActivityChartOption(snapshots, theme = {}) {
  return {
    ...baseLineChartOption(theme, {
      legendNames: ["Workers", "Users"],
      yAxisFormatter: (value) => formatCount(value) || value,
    }),
    series: [
      { name: "Workers", type: "line", showSymbol: false, data: toTimeSeries(snapshots, (s) => s.workers) },
      { name: "Users", type: "line", showSymbol: false, data: toTimeSeries(snapshots, (s) => s.users) },
    ],
  };
}

export function buildActivityChartSummary(snapshots) {
  const workers = snapshots.map((s) => s.workers).filter((v) => Number.isFinite(v));
  const users = snapshots.map((s) => s.users).filter((v) => Number.isFinite(v));
  if (workers.length === 0 && users.length === 0) return "Worker and user counts -- no data available.";
  const latestWorkers = workers.length > 0 ? formatCount(workers[workers.length - 1]) : "no data";
  const latestUsers = users.length > 0 ? formatCount(users[users.length - 1]) : "no data";
  return `Worker and user counts over ${snapshots.length} snapshots -- most recently ${latestWorkers} workers, ${latestUsers} users.`;
}

// Order here is the single source of truth for both the spec-building
// below and defaultRender's positional canvas-node matching -- every
// render lists these in this same fixed order, so index-based reuse
// (no per-chart identifier needed) is safe.
const CHART_DEFS = [
  { key: "hashrate", title: "Pool Hashrate", buildOption: buildHashrateChartOption, buildSummary: buildHashrateChartSummary },
  { key: "shares", title: "Accepted / Rejected Shares", buildOption: buildSharesChartOption, buildSummary: buildSharesChartSummary },
  { key: "difficulty", title: "Highest Difficulty", buildOption: buildDifficultyChartOption, buildSummary: buildDifficultyChartSummary },
  { key: "activity", title: "Workers / Users", buildOption: buildActivityChartOption, buildSummary: buildActivityChartSummary },
];

// -------------------------------------------------------------------
// Pure page-spec building
// -------------------------------------------------------------------

function loadingSectionSpec() {
  return el("div", {
    className: "history-page__loading",
    children: [
      loadingSkeletonSpec({
        shape: "block",
        height: 280,
        count: CHART_DEFS.length,
        // Only grouped-"block" call site in the project -- the grouped-
        // "tile" callers already have their own gap via className:
        // "tile-grid", and grouped-"row" callers already have their own
        // per-item margin-bottom (loading-skeleton.css). This modifier
        // is what gives *this* group a gap without touching either of
        // those already-correct cases (Code Reviewer caught a prior
        // version of this fix incorrectly widening every row group's
        // spacing by inferring "not tile-grid" instead of naming this
        // one explicitly).
        className: "loading-skeleton-group--stacked",
      }),
    ],
  });
}

export function buildHistorySpec(state) {
  const heading = el("h1", { className: "history-page__title", text: "Historical Analytics" });

  if (state.status === "loading") {
    return el("div", { className: "history-page", children: [heading, loadingSectionSpec()] });
  }

  if (state.status === "error") {
    return el("div", {
      className: "history-page",
      children: [heading, errorBannerSpec({ message: describeHistoryFetchError(state.error), icon: "error" })],
    });
  }

  const banners = [];
  if (state.error) {
    banners.push(errorBannerSpec({ message: describeHistoryFetchError(state.error), icon: "error" }));
  } else if (state.isStale) {
    const latest = state.data.snapshots[state.data.snapshots.length - 1];
    banners.push(errorBannerSpec({ message: staleMessage(latest && latest.timestamp), icon: "warning" }));
  }

  // Section 5's diagram lists this page's components tersely as
  // "ChartPanel x N" with no explicit EmptyState -- but Section 16's
  // three-state requirement (Loading/Error/Empty) is a blanket
  // architectural rule applied to every view, not opted into per page
  // by the diagram; every other list-style page (Pool/Users/Workers/
  // Ticker) already treats it that way, so this page does too.
  if (state.status === "empty") {
    return el("div", {
      className: "history-page",
      children: [
        heading,
        ...banners,
        cardSpec({ children: [emptyStateSpec({ message: "No historical data has been recorded yet." })] }),
      ],
    });
  }

  if (state.status !== "success") {
    throw new Error(`buildHistorySpec: unrecognized status "${state.status}"`);
  }

  const charts = CHART_DEFS.map((def) =>
    chartPanelSpec({
      title: def.title,
      summary: def.buildSummary(state.data.snapshots),
    }),
  );

  return el("div", {
    className: "history-page",
    children: [heading, ...banners, ...charts],
  });
}

// -------------------------------------------------------------------
// DOM glue -- mount/unmount lifecycle
// -------------------------------------------------------------------

const EMPTY_PAGE_SPEC = el("div", { className: "history-page" });

// Generalises overview.js's/pool.js's/*-detail.js's single-canvas swap
// to an array of canvas nodes, one per CHART_DEFS entry, matched
// positionally (document order === CHART_DEFS order, always, since the
// spec above always renders them in that fixed sequence).
function defaultRender(container, spec, { reuseCanvasNodes = [] } = {}) {
  const node = specToDom(spec);
  const freshCanvasNodes = Array.from(node.querySelectorAll(".chart-panel__canvas"));

  const canvasNodes = freshCanvasNodes.map((freshNode, index) => {
    const reuseNode = reuseCanvasNodes[index];
    if (reuseNode && freshNode && freshNode.parentNode) {
      freshNode.parentNode.replaceChild(reuseNode, freshNode);
      return reuseNode;
    }
    return freshNode;
  });

  container.replaceChildren(node);
  return canvasNodes;
}

function emptyChartSlots() {
  return CHART_DEFS.map(() => null);
}

// Injectable (tests can capture calls without polluting test output);
// defaults to console.error rather than silently discarding, since
// this project has no other error-reporting/telemetry mechanism to
// hook into and "reported nowhere" was the specific gap this callback
// exists to close.
function defaultOnChartError(error, context) {
  if (typeof console !== "undefined" && console.error) {
    console.error(`history.js: ${context}`, error);
  }
}

let isMounted = false;
let mountToken = 0;
let chartHandles = emptyChartSlots();
let chartCanvasNodes = emptyChartSlots();
let renderedStatus = null;
let lastSnapshots = null;
let lastAppliedTheme = null;
let stopPollingFn = null;
let stopThemeSubscription = null;
let currentRender = defaultRender;
let currentContainer = null;

function disposeAllCharts() {
  chartHandles.forEach((handle) => {
    if (handle) handle.dispose();
  });
  chartHandles = emptyChartSlots();
  chartCanvasNodes = emptyChartSlots();
}

export function mount(
  container,
  {
    fetchImpl,
    intervalMs,
    staleAfterMs,
    render = defaultRender,
    createChartImpl = createChart,
    readThemeTokensImpl = readThemeTokens,
    onChartError = defaultOnChartError,
  } = {},
) {
  if (isMounted) {
    throw new Error("history.mount: already mounted -- call unmount() first");
  }
  isMounted = true;
  mountToken += 1;
  const myToken = mountToken;

  chartHandles = emptyChartSlots();
  chartCanvasNodes = emptyChartSlots();
  renderedStatus = null;
  lastSnapshots = null;
  stopPollingFn = null;
  stopThemeSubscription = null;
  currentRender = render;
  currentContainer = container;
  lastAppliedTheme = getState().theme;

  function isCurrent() {
    return isMounted && mountToken === myToken;
  }

  const safeStaleAfterMs = Number.isFinite(staleAfterMs) && staleAfterMs > 0 ? staleAfterMs : undefined;
  // No `validate: validateSchema` -- see the module comment. This
  // endpoint's own shape check is isValidHistoricalData. staleAfterMs
  // is deliberately not forwarded to fetchEndpoint either (see the
  // module comment) -- it is applied locally in deriveHistoryState
  // instead, from handleResult below.
  const fetchOptions = { fetchImpl, validate: isValidHistoricalData };

  function renderState(historyState) {
    const reuseCharts = renderedStatus === "success" && historyState.status === "success";

    if (!reuseCharts) {
      disposeAllCharts();
    }

    const spec = buildHistorySpec(historyState);
    const canvasNodes = render(container, spec, {
      reuseCanvasNodes: reuseCharts ? chartCanvasNodes : [],
    });
    renderedStatus = historyState.status;

    if (historyState.status === "success" && Array.isArray(canvasNodes) && canvasNodes.length === CHART_DEFS.length) {
      lastSnapshots = historyState.data.snapshots;
      const theme = buildEChartsTheme(readThemeTokensImpl());
      CHART_DEFS.forEach((def, index) => {
        // Each of the four charts is independent -- one chart's
        // failure (a malformed option, an ECharts init error, e.g.
        // window.echarts not yet loaded) must not prevent every
        // *later* CHART_DEFS entry in this same forEach from being
        // created/updated. Left null (not left holding a possibly-
        // half-initialized handle) so the next render can still retry
        // creating this one fresh, rather than being permanently
        // wedged on a chart that never successfully initialized.
        try {
          const option = def.buildOption(lastSnapshots, theme);
          if (reuseCharts && chartHandles[index]) {
            chartHandles[index].update(option);
          } else {
            chartHandles[index] = createChartImpl(canvasNodes[index], option);
          }
          chartCanvasNodes[index] = canvasNodes[index];
        } catch (error) {
          chartHandles[index] = null;
          chartCanvasNodes[index] = null;
          onChartError(error, def.key);
        }
      });
    } else {
      chartCanvasNodes = emptyChartSlots();
    }
  }

  function handleResult(result) {
    try {
      renderState(deriveHistoryState({ payload: result.payload, error: result.error, staleAfterMs: safeStaleAfterMs }));
    } catch (error) {
      // Defence in depth: the per-chart try/catch above already
      // isolates the one currently-reachable throw site inside
      // renderState, but an unguarded exception anywhere else on this
      // path would otherwise become an unhandled promise rejection on
      // the very first fetch -- leaving the page stuck on its loading
      // skeleton forever with no visible indication anything went
      // wrong -- or, on a later poll tick, get silently discarded by
      // startPolling's own no-onError-supplied default (core/api.js).
      onChartError(error, "renderState");
    }
  }

  renderState({ status: "loading" });

  stopThemeSubscription = subscribe((appState) => {
    if (!isCurrent()) return;
    if (appState.theme === lastAppliedTheme) return;
    lastAppliedTheme = appState.theme;
    if (renderedStatus === "success" && lastSnapshots) {
      const theme = buildEChartsTheme(readThemeTokensImpl());
      CHART_DEFS.forEach((def, index) => {
        if (!chartHandles[index]) return;
        try {
          chartHandles[index].update(def.buildOption(lastSnapshots, theme));
        } catch (error) {
          onChartError(error, `${def.key}-theme-repaint`);
        }
      });
    }
  });

  (async () => {
    const result = await fetchEndpoint(HISTORY_ENDPOINT, fetchOptions);
    if (!isCurrent()) return;
    handleResult(result);

    if (Number.isFinite(intervalMs) && intervalMs > 0) {
      stopPollingFn = startPolling(
        HISTORY_ENDPOINT,
        intervalMs,
        (pollResult) => {
          if (!isCurrent()) return;
          handleResult(pollResult);
        },
        fetchOptions,
      );
    }
  })();
}

export function unmount() {
  if (!isMounted) return;
  isMounted = false;
  if (stopThemeSubscription) {
    stopThemeSubscription();
    stopThemeSubscription = null;
  }
  if (stopPollingFn) {
    stopPollingFn();
    stopPollingFn = null;
  }
  disposeAllCharts();
  renderedStatus = null;
  lastSnapshots = null;
  currentRender(currentContainer, EMPTY_PAGE_SPEC);
  currentContainer = null;
}
